#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Máquina Virtual'
        hostname: ubuntu-vm
        username: vm
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - gimp
        - open-vm-tools
        - neofetch
    snaps:
        - name: chromium
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: false
    updates: false
    shutdown: reboot
